# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-DDDS
version:      0.01
version_from: lib/Net/DDDS.pm
installdirs:  site
requires:
    Net::DNS:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
